# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for representing attribute domains.

A categorical attribute can be characterized by a finite set of possible
values. A numerical attribute can be characterized by a range of possible
values. A free-form text attribute represents unstructured text fields that
may be generated by a language model. In typical differential privacy
scenarios, it is assumed/required that the domain is known in advance. This
module provides dataclasses for representing this information.

In this library we provide special treatment for out-of-domain values.  There
are two ways that we support handling out-of-domain values: (1) directly model
them or (2) map them to an element of the domain.

Values from categorical attributes that are not in the list of possible values
are mapped to some value in the list (default is the first element).
For safety, it's best practice to add a typed sentinel (e.g. ``"Unknown"`` for
strings, ``-1`` for ints) as the first entry in the list of possible values for
categorical attributes if you are unsure if there are out-of-domain values.
If you know there are not any out-of-domain values, then you can (and should)
ignore this advice, so that downstream mechanisms don't generate out-of-domain
values when none should exist.

Similarly, values from numerical attributes that are outside of the range
[min_value, max_value] (or not even a numerical type) are clipped to this range
if `clip_to_range=True`. Otherewise, they are mapped to a special out-of-domain
value.  As before we recommend setting clip_to_range=False to directly model
out-of-domain values.  If you are sure none should exist, you can (and should)
ignore this advice, so that downstream mechanisms don't generate out-of-domain
values when none should exist.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
import dataclasses
import functools
import math
import pathlib

from typing import Any, Literal, TypeAlias

import numpy as np
import yaml

PathType = pathlib.Path

CategoricalValue: TypeAlias = bool | int | str

IntervalHandling = Literal['midpoint', 'sample', 'interval']


@dataclasses.dataclass(frozen=True)
class CategoricalAttribute:
  """Dataclass for storing metadata about a categorical attribute.

  If the set of possible values is known in advance, this should be be
  specified via the ``possible_values`` attribute. If a value does not exist
  in this list, it will be mapped to ``possible_values[out_of_domain_index]``.
  If your data does not contain out-of-domain values, this will be a no-op.

  All values in ``possible_values`` must share the same type, which must be one
  of ``bool``, ``int``, ``float``, or ``str``.  ``None`` is not allowed; use a
  typed sentinel instead (e.g. ``"Unknown"`` for strings, ``-1`` for ints).

  If the set of possible values is not known in advance, use the
  OpenSetCategoricalAttribute class instead.

  Attributes:
    possible_values: A homogeneous sequence of possible values for this
      attribute. All values must share the same type (one of bool, int, float,
      or str).
    out_of_domain_index: The index into possible_values that out-of-domain
      values should be mapped to.
    description: An optional semantic description of the attribute.
  """

  possible_values: Sequence[CategoricalValue]
  out_of_domain_index: int = 0
  description: str | None = None

  def __post_init__(self):
    # Coerce to a list to preserve the former attrs ``converter=list`` behavior
    # (accept any iterable and normalize the stored type).
    object.__setattr__(self, 'possible_values', list(self.possible_values))
    if self.size == 0:
      raise ValueError('Possible values must not be empty.')
    if self.out_of_domain_index < 0 or self.out_of_domain_index >= self.size:
      raise ValueError(
          f'out_of_domain_index must be in [0, {self.size-1}], got'
          f' {self.out_of_domain_index}.'
      )
    _allowed_types = (bool, int, float, str)
    types = {type(v) for v in self.possible_values}
    if len(types) != 1 or next(iter(types)) not in _allowed_types:
      raise ValueError(
          'possible_values must be homogeneous and all bool, int, float, or'
          f' str, got types {types}.'
      )

  @functools.cached_property
  def size(self) -> int:
    """Returns the number of possible values."""
    return len(self.possible_values)

  def standardize(self, value: Any) -> CategoricalValue:
    """Standardizes a value to one of the possible values."""
    if value in self.possible_values:
      return value
    return self.possible_values[self.out_of_domain_index]

  @functools.cached_property
  def lookup(self) -> dict[str, int]:
    """Returns a mapping from stringified values to their indices."""
    return {str(v): i for i, v in enumerate(self.possible_values)}


@dataclasses.dataclass(frozen=True)
class OpenSetCategoricalAttribute:
  """A categorical attribute of strings with unknown domain.

  Given an attribute with an unknown domain, we will attempt to automatically
  infer the set of possible values from the data in a DP manner. Values that
  do not appear frequently enough will be mapped to a default value.

  Discovered values are always represented as strings.

  Attributes:
    default_value: The default string value for out-of-domain entries.
      Partitions that do not meet the threshold will be mapped to this value.
    public_possible_values: Values guaranteed to be in-domain. Partition
      selection always retains these regardless of thresholding.
    description: An optional semantic description of the attribute.
  """

  default_value: str = '<OOD>'
  public_possible_values: Sequence[str] = ()
  description: str | None = None

  def __post_init__(self):
    object.__setattr__(
        self, 'public_possible_values', list(self.public_possible_values)
    )


@dataclasses.dataclass(frozen=True)
class NumericalAttribute:
  """Dataclass for storing metadata about a numerical attribute.

  We require knowing the range of possible values in advance, and these must be
  specified via the `min_value` and `max_value` attributes. If
  `out_of_domain_allowed` is True, out-of-domain values will be mapped to
  `None`. If it is False, out-of-domain values will be clipped to
  (min_value, max_value) if they are a numeric type, and to min_value otherwise.

  Attributes:
    min_value: The minimum possible value for this attribute (inclusive).
    max_value: The maximum possible value for this attribute (inclusive).
    clip_to_range: Specifies how out-of-domain values should be treated. If
      True, out-of-domain values will be clipped to the range [min_value,
      max_value] if they are a numeric type, and to min_value otherwise.  If
      False, out-of-domain values will be grouped together and treated as a
      single special out-of-domain value.
    sentinel: The value to assign to out-of-domain entries during reverse
      discretization when ``clip_to_range`` is False. Defaults to ``None``,
      which resolves to ``np.nan`` for numeric modes or ``''`` for
      ``interval_handling='interval'``. Set to an integer (e.g. ``-1``) to keep
      the output array as an integer dtype instead of silently promoting to
      float. When explicitly set, must be a string for interval mode and numeric
      for other modes. Use ``resolved_sentinel`` to get the effective value.
    dtype: The dtype of the data (either 'int' or 'float').
    interval_handling: Controls how discretized intervals are converted back to
      numerical values. 'midpoint' returns the interval midpoint (or the finite
      endpoint if the other is infinite). 'sample' draws uniformly from the
      interval (or returns the finite endpoint if the other is infinite).
      'interval' keeps the interval (string) in the output unchanged.
    description: An optional semantic description of the attribute.
  """

  min_value: float
  max_value: float
  clip_to_range: bool = True
  sentinel: float | int | str | None = None
  dtype: str = 'float'
  interval_handling: str = 'midpoint'
  description: str | None = None

  def __post_init__(self):
    # Coerce to float to preserve the former attrs ``converter=float`` behavior;
    # the checks below mirror the former attrs validators (run in field order).
    object.__setattr__(self, 'min_value', float(self.min_value))
    object.__setattr__(self, 'max_value', float(self.max_value))
    if self.min_value >= self.max_value:
      raise ValueError(
          f'min_value ({self.min_value}) must be strictly less than'
          f' max_value ({self.max_value}).'
      )
    if self.dtype not in ['int', 'float']:
      raise ValueError(
          f'dtype must be either "int" or "float", got {self.dtype}.'
      )
    if self.interval_handling not in ['midpoint', 'sample', 'interval']:
      raise ValueError(
          'interval_handling must be "midpoint", "sample", or "interval",'
          f' got {self.interval_handling}.'
      )
    if self.sentinel is not None:
      if self.interval_handling == 'interval':
        if not isinstance(self.sentinel, str):
          raise ValueError(
              "interval_handling='interval' requires a string sentinel, got"
              f' sentinel={self.sentinel!r}.'
          )
      elif not isinstance(self.sentinel, (int, float, np.integer, np.floating)):
        raise ValueError(
            'sentinel must be numeric when'
            f' interval_handling={self.interval_handling!r}, got'
            f' sentinel={self.sentinel!r}.'
        )

  @property
  def resolved_sentinel(self) -> float | int | str:
    """Returns the effective sentinel, with mode-appropriate defaults."""
    if self.sentinel is not None:
      return self.sentinel
    if self.interval_handling == 'interval':
      return ''
    return np.nan

  @property
  def exclusive_min_value(self) -> float:
    """Returns the exclusive minimum value for this attribute."""
    if self.dtype == 'int':
      return self.min_value - 1
    return math.nextafter(self.min_value, -math.inf)

  @property
  def exclusive_max_value(self) -> float:
    """Returns the exclusive maximum value for this attribute."""
    if self.dtype == 'int':
      return self.max_value + 1
    return math.nextafter(self.max_value, math.inf)

  def standardize(self, value: Any) -> int | float:
    """Standardizes a value to one of the possible values."""
    if self.clip_to_range:
      low_value = invalid_value = self.min_value
      high_value = self.max_value
    else:
      low_value = high_value = invalid_value = float('nan')
    try:
      value = float(value)  # works for anything that converts to float.
      if math.isnan(value):
        return invalid_value
      elif value < self.min_value:
        return low_value
      elif value > self.max_value:
        return high_value
      elif self.dtype == 'int':
        return round(value)
      return value
    except (ValueError, TypeError):
      return invalid_value


@dataclasses.dataclass(frozen=True)
class FreeFormTextAttribute:
  """Dataclass for storing metadata about a free-form text attribute.

  Represents an unstructured text field whose values may be generated by a
  language model.  Generated text will be truncated to `max_tokens` tokens.

  Attributes:
    max_tokens: Maximum number of tokens for this text field. Generated outputs
      will be truncated to this length.
    description: An optional semantic description of the attribute.
    formatting: Optional formatting requirements (e.g., structural constraints
      the text must conform to).
    exemplar: An optional example value for this attribute.
  """

  max_tokens: int = 256
  description: str | None = None
  formatting: str | None = None
  exemplar: str | None = None


AttributeType = (
    CategoricalAttribute
    | NumericalAttribute
    | OpenSetCategoricalAttribute
    | FreeFormTextAttribute
)


@dataclasses.dataclass(frozen=True, eq=False)
class Schema(Mapping[str, AttributeType]):
  """Schema defining attribute domains and optional cross-attribute constraints.

  Implements ``collections.abc.Mapping[str, AttributeType]`` so it can be
  indexed like a dictionary (e.g. ``schema['col']``, ``'col' in schema``,
  ``len(schema)``, ``for col in schema``).

  Attributes:
    attributes: Mapping from column names to attribute domain specifications.
    constraints: Cross-attribute constraints associated with this schema.
  """

  attributes: Mapping[str, AttributeType]
  constraints: Sequence[Any] = ()

  def __post_init__(self):
    if isinstance(self.constraints, list):
      object.__setattr__(self, 'constraints', tuple(self.constraints))

  def __getitem__(self, key: str) -> AttributeType:
    return self.attributes[key]

  def __contains__(self, key: object) -> bool:
    return key in self.attributes

  def __iter__(self) -> Any:
    return iter(self.attributes)

  def __len__(self) -> int:
    return len(self.attributes)

  def __eq__(self, other: object) -> bool:
    if isinstance(other, Schema):
      return (
          self.attributes == other.attributes
          and self.constraints == other.constraints
      )
    if isinstance(other, Mapping):
      return not self.constraints and self.attributes == other
    return False


def to_yaml_file(
    domain: Schema | Mapping[str, AttributeType], filepath: str | PathType
) -> None:
  """Writes a Schema or dictionary of Attribute objects to a YAML file."""
  yaml_data = {}
  for name, attr_obj in domain.items():
    attr_data = dataclasses.asdict(attr_obj)
    attr_data['type'] = attr_obj.__class__.__name__
    yaml_data[name] = attr_data
  with open(filepath, 'w') as f:
    yaml.dump(yaml_data, f, default_flow_style=False)


def from_yaml_file(filepath: str | PathType) -> Schema:
  """Reads a Schema from a YAML file."""
  with open(filepath, 'r') as f:
    yaml_data = yaml.safe_load(f)
  attrs = {}
  for name, attr_data in yaml_data.items():
    attr_type = attr_data.pop('type', None)
    if attr_type == 'CategoricalAttribute' or 'possible_values' in attr_data:
      attrs[name] = CategoricalAttribute(**attr_data)
    elif attr_type == 'NumericalAttribute' or 'min_value' in attr_data:
      attrs[name] = NumericalAttribute(**attr_data)
    elif attr_type == 'FreeFormTextAttribute' or 'max_tokens' in attr_data:
      attrs[name] = FreeFormTextAttribute(**attr_data)
    elif (
        attr_type == 'OpenSetCategoricalAttribute'
        or 'default_value' in attr_data
        or not attr_data
    ):
      attrs[name] = OpenSetCategoricalAttribute(**attr_data)
    else:
      raise ValueError(f'Invalid YAML data for attribute: {name}')
  return Schema(attrs)
